name: Super-Linter

on: push

jobs: 
 super-lint:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Install pylint
     run: pip install pylint

   - name: Run pylint
     uses: suo/pylint-github-action@releases/v1
     env: 
       DEFAULT_BRANCH: main
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
